INSERT INTO `commodity` (`id`, `name`, `price`, `unit`, `sold`, `main_pic_url`, `msg`) VALUES (6, 'Peter Marshall', 343.13, '200g', 984, '/images/goods/ml.png', 'k3uEyaoEPD');
INSERT INTO `commodity` (`id`, `name`, `price`, `unit`, `sold`, `main_pic_url`, `msg`) VALUES (7, 'Tian Jialun', 214.11, '300g', 686, '/images/goods/ml.png', 'WpJ8NMGw8p');
INSERT INTO `commodity` (`id`, `name`, `price`, `unit`, `sold`, `main_pic_url`, `msg`) VALUES (8, 'April Coleman', 355.96, '700g', 280, '/images/goods/ml.png', 'oErXPgZkv3');
INSERT INTO `commodity` (`id`, `name`, `price`, `unit`, `sold`, `main_pic_url`, `msg`) VALUES (9, 'Esther White', 909.37, '700g', 564, '/images/goods/ml.png', 'XHs0IuY344');
INSERT INTO `commodity` (`id`, `name`, `price`, `unit`, `sold`, `main_pic_url`, `msg`) VALUES (10, 'Liao Yu Ling', 115.90, '500g', 874, '/images/goods/ml.png', 'cbbkq3mwND');
INSERT INTO `commodity` (`id`, `name`, `price`, `unit`, `sold`, `main_pic_url`, `msg`) VALUES (11, 'Nakamura Rena', 620.43, '300g', 461, '/images/goods/ml.png', 'CWe3AGiUcw');
INSERT INTO `commodity` (`id`, `name`, `price`, `unit`, `sold`, `main_pic_url`, `msg`) VALUES (12, 'Ku Lik Sun', 696.29, '100g', 832, '/images/goods/ml.png', 'LSSaVbkTLa');
INSERT INTO `commodity` (`id`, `name`, `price`, `unit`, `sold`, `main_pic_url`, `msg`) VALUES (13, 'Mo Wing Suen', 601.84, '200g', 554, '/images/goods/ml.png', '2vRfBeJFn3');
INSERT INTO `commodity` (`id`, `name`, `price`, `unit`, `sold`, `main_pic_url`, `msg`) VALUES (14, 'Pan Jialun', 591.73, '700g', 464, '/images/goods/ml.png', 'uQzUIrzXdS');
INSERT INTO `commodity` (`id`, `name`, `price`, `unit`, `sold`, `main_pic_url`, `msg`) VALUES (15, 'Ye Zhennan', 232.93, '300g', 120, '/images/goods/ml.png', 'Xps3IGfVn2');
INSERT INTO `commodity` (`id`, `name`, `price`, `unit`, `sold`, `main_pic_url`, `msg`) VALUES (16, 'Tony Ross', 789.00, '800g', 846, '/images/goods/ml.png', '8vZP5b7JYk');
INSERT INTO `commodity` (`id`, `name`, `price`, `unit`, `sold`, `main_pic_url`, `msg`) VALUES (17, 'Hasegawa Mitsuki', 408.47, '500g', 998, '/images/goods/ml.png', 'yDtJlNmT90');
INSERT INTO `commodity` (`id`, `name`, `price`, `unit`, `sold`, `main_pic_url`, `msg`) VALUES (18, 'Wu Sze Yu', 468.65, '600g', 766, '/images/goods/ml.png', '36ZPB5jume');
INSERT INTO `commodity` (`id`, `name`, `price`, `unit`, `sold`, `main_pic_url`, `msg`) VALUES (19, 'Lui Wing Fat', 844.98, '700g', 17, '/images/goods/ml.png', 'VE6u4JbYTz');
INSERT INTO `commodity` (`id`, `name`, `price`, `unit`, `sold`, `main_pic_url`, `msg`) VALUES (20, 'Yuen Sum Wing', 922.58, '800g', 888, '/images/goods/ml.png', 'NlOoUhw1E2');
INSERT INTO `commodity` (`id`, `name`, `price`, `unit`, `sold`, `main_pic_url`, `msg`) VALUES (21, 'Gao Zhennan', 799.31, '900g', 627, '/images/goods/ml.png', 'UCUNbIFxz8');
INSERT INTO `commodity` (`id`, `name`, `price`, `unit`, `sold`, `main_pic_url`, `msg`) VALUES (22, 'Xiang Lu', 582.63, '700g', 683, '/images/goods/ml.png', '5HhuTSwOOp');
INSERT INTO `commodity` (`id`, `name`, `price`, `unit`, `sold`, `main_pic_url`, `msg`) VALUES (23, 'Fong Wing Sze', 795.71, '600g', 130, '/images/goods/ml.png', '1sEFVTdhnH');
INSERT INTO `commodity` (`id`, `name`, `price`, `unit`, `sold`, `main_pic_url`, `msg`) VALUES (24, 'Joseph Thompson', 160.60, '300g', 952, '/images/goods/ml.png', '3MosND4sQ5');
INSERT INTO `commodity` (`id`, `name`, `price`, `unit`, `sold`, `main_pic_url`, `msg`) VALUES (25, 'Jeffrey Tran', 330.46, '400g', 584, '/images/goods/ml.png', 'iu1Isa7AKG');
