spring.application.name=petserver
server.local-address=localhost:3000
server.port=3000

# database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis-Plus
mybatis-plus.mapper-locations=classpath:mapper/*.xml
mybatis-plus.type-aliases-package=com.yellow.petshop.model

# static res
spring.mvc.static-path-pattern=/images/**
spring.web.resources.static-locations=classpath:/static/
